name: violet
description: Open Source Hentai Viewer App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.30.1+0

publish_to: none

environment:
  sdk: ^3.0.0
  flutter: "3.3.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # I know there are too many packages.
  android_intent_plus: ^3.1.0
  animated_widgets: ^1.1.0
  animations:
  async:
  auto_animated: ^3.0.1
  azlistview:
    git: https://github.com/violet-dev/azlistview 
  badges: ^3.1.2
  bloc: ^8.1.2
  bubble_tab_indicator: ^0.1.6
  # cached_network_image: ^3.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  # charts_flutter: ^0.11.0
  # charts_flutter: # https://github.com/google/charts/issues/678
  #   git:
  #     url: https://github.com/google/charts
  #     path: charts_flutter
  # charts_flutter: ^0.12.0
  community_charts_flutter: ^1.0.1
  connectivity:
  convert:
  country_pickers: ^2.0.0
  crypto:
  # device_info: ^2.0.0
  device_info_plus: ^9.0.2
  dio: ^5.0.0
  dio_cache_interceptor: ^3.3.1
  draggable_scrollbar:
  # dynamic_theme: ^1.0.1
  dynamic_theme:
    git: https://github.com/Norbert515/dynamic_theme
  encrypt: ^5.0.0
  expandable: ^5.0.1
  extended_image: ^8.1.1
  ffi: ^2.0.2
  file_picker: ^5.5.0
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.0.12
  # flare_dart:
  flare_flutter: ^3.0.2
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.3
  flutter_downloader: ^1.11.3
  flutter_heatmap_calendar: ^1.0.5
  flutter_image_compress: ^2.0.4
  flutter_inappwebview: ^5.8.0
  flutter_markdown:
  flutter_mobx:
  flutter_reorderable_list:
  flutter_keyboard_visibility: ^5.1.1
  flutter_speed_dial: ^7.0.0
  flutter_staggered_animations:
    git: https://github.com/mfrischbutter/flutter_staggered_animations
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.0.0
  flutter_js: ^0.8.0
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.2.4
  freezed_annotation:
  get: ^4.6.6
  gradient_widgets: ^0.6.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^1.1.0
  image_crop:
    git: https://github.com/litang0908/image_crop
  image_size_getter: ^2.1.2
  intl: ^0.18.0
  kdtree: ^0.2.0
  local_auth: ^2.1.6
  lottie:
  material_design_icons_flutter: ^5.0.6595
  mdi: ^5.0.0-nullsafety.0
  modal_bottom_sheet: ^3.0.0-pre
  open_file: ^3.3.1
  path:
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  platform: ^3.1.0
  pimp_my_button:
    git: https://github.com/MichaelMarner/pimp_my_button
  pointycastle:
  provider: ^6.0.2
  # scrollable_positioned_list: ^0.3.2
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2
  sticky_headers: "^0.3.0"
  synchronized:
  timeago:
  tuple:
  uni_links: ^0.5.1
  url_launcher: ^6.1.10
  uuid:
  # wakelock: ^0.6.2
  webview_flutter: ^3.0.0
  collection: ^1.16.0
  octo_image: ^2.0.0
  dart_git:
    git: https://github.com/GitJournal/dart-git
  go_git_dart:
    git: https://github.com/GitJournal/go_git_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  drift_sqflite: ^2.0.0
  sqflite_common_ffi:
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/locale/
    - assets/locale/tag/
    - assets/rank/

    - assets/images/

    - assets/flare/Cosmos.flr
    - assets/flare/search_close.flr

    - assets/flare/Loading.flr
    - assets/flare/Loading2.flr
    - assets/flare/Trim.flr
    - assets/flare/SlidinSquaresLoader.flr
    - assets/flare/switch_daytime.flr
    - assets/flare/likeUtsua.flr

    - assets/lottie/3227-error-404-facebook-style.json
    - assets/lottie/5040-shooting-star.json
    - assets/lottie/26438-drone-flight.json
    - assets/lottie/24208-menhera-chan-at-cocopry-sticker-10.json
    - assets/lottie/28395-hajj-mabroor-infographic-animation.json
    - assets/lottie/28446-floward-gift-box.json

    - assets/icons/pixiv.ico

    - assets/p7zip/arm64-v8a/lib7zr.so # @dependent: android
    - assets/p7zip/armeabi-v7a/lib7zr.so # @dependent: android
    - assets/p7zip/x86/lib7zr.so # @dependent: android
    - assets/p7zip/x86_64/lib7zr.so # @dependent: android

    - assets/webview/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: assets/SF-Pro-Text-Regular.otf

    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/SF-Pro-Text-Bold.otf

    - family: Calibre-Semibold
      fonts:
        - asset: assets/Calibre-Semibold.otf

    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons.ttf
