[package]
name = "rust_lib_violet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.24"
sevenz-rust = { version = "0.6.1" }

[dev-dependencies]
tokio = { version = "1.0.0" }
